name: Rust

on:
  workflow_dispatch:
    inputs:
      draft:
        description: 'Should this release be a draft?'
        required: false
        default: false
        type: boolean

env:
  CARGO_TERM_COLOR: always

jobs:
  tests:
    name: Build and run tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Build
      run: cargo build --verbose
      
    - name: Run tests
      run: cargo test --verbose

  create-release:
    name: Create release on Github
    runs-on: ubuntu-latest
    outputs: 
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: create_release 
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: ${{ inputs.draft }}
          prerelease: false
      
  upload-release:
    name: Build and upload release artifacts
    needs: [ tests, create-release ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
          target: x86_64-unknown-linux-musl
          
      - name: Install musl-tools
        run: sudo apt-get install -y --no-install-recommends musl-tools
        
      - name: Build release binary
        run: cargo build --release
        
      - name: Create checksum
        id: make-checksum
        working-directory: ./target/release
        run: |
          ls -la
          name="gradle-deps-differ-stable.sha256sum"
          sha256sum "gradle-deps-differ" > "${name}"
          echo "checksum_name=${name}" >> "$GITHUB_OUTPUT"

      - name: Tar release
        id: make-artifact
        working-directory: ./target/release
        run: |
          name="gradle-deps-differ-stable.tar.gz"
          tar cvzf "${name}" "gradle-deps-differ"
          echo "tar_name=${name}" >> "$GITHUB_OUTPUT"

      - name: Upload release archive
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }} 
          asset_path: ./target/release/${{ steps.make-artifact.outputs.tar_name }}
          asset_name: gradle-deps-differ-stable.tar.gz
          asset_content_type: application/octet-stream
          
      - name: Upload checksum
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }} 
          asset_path: ./target/release/${{ steps.make-checksum.outputs.name }}
          asset_name: gradle-deps-differ-stable.sha256sum
          asset_content_type: text/plain
